// Shared "which countries would you work in" list — was previously defined
// inline inside src/auth/Signup/SignupSecondStep.tsx only, with no way to
// edit the choice again after signup. Extracted here so
// src/more/JobPreferences.tsx (the "change it later" settings screen) can
// use the exact same list without drifting out of sync with signup.
export const COUNTRIES = [
  'Remote - Anywhere',
  'United States',
  'United Kingdom',
  'Canada',
  'Ireland',
  'Germany',
  'France',
  'Spain',
  'Portugal',
  'Italy',
  'Switzerland',
  'Austria',
  'Belgium',
  'Netherlands',
  'Luxembourg',
  'Denmark',
  'Sweden',
  'Norway',
  'Finland',
  'Iceland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Greece',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Australia',
  'New Zealand',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Hong Kong',
  'Taiwan',
  'Japan',
  'South Korea',
  'China',
  'India',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Israel',
  'Turkey',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Ghana',
  'South Africa',
  'Morocco',
  'Brazil',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Costa Rica',
  'Uruguay',
];
